id: I74B98257
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T14:17:23.928676'
last_modified: '2022-06-19T14:17:23.928688'
parser: null
source_metadata:
  title: New Red Annals
  author: annals
  description: Digital version 1.0 {Tibetan}; unrevised, thematic TEI markup
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Rime Centre Moscow, OCR-processed
  - Editorial process:Mathias Fermer (mf), Kunga Dorje (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:Kunga Dorje (kun)
  text_witnesses: https://sakyaresearch.org/sources/113
  bases:
    5c78:
      title: New Red Annals
      order: 1
      base_file: 5c78.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
